version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/" # Lambda関数の依存関係を監視
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    labels:
      - "security"
      - "dependencies"
